#Basic Settings
title: Chris Blyth
description: "Redirects site"
url: https://redirects.blyth.me.uk
author: BlythMeister
logo: /images/me.png
lang: en_GB

GoogleAnalytics: G-51T4HE9ZTW

#Webmaster tools
#webmaster_verifications:
#  google: HV11HFJBxWBjSBdvj2X1ARYcyV0gkh2RC2RN-BBPOQc
#  bing: 70C9C40BE160CF8A17564E2F00B21581

#Social
twitter:
    username: BlythMeister
    card: summary

facebook:
   app_id: 1934053506806190
   publisher: 285001657
   admins: 285001657

social:
    name: Chris Blyth
    links:
        - https://www.twitter.com/BlythMeister
        - https://www.linkedin.com/in/chris-blyth/
        - https://github.com/BlythMeister
        - https://open.spotify.com/user/BlythMeister

#Link format
permalink: pretty

#Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      image: /images/me.png

#Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gist
